version: '3.8'
services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: electricity
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  back:
    build:
      context: ./back
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/electricity?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql

  front:
    image: node:18
    working_dir: /workspace/front
    volumes:
      - ./front:/workspace/front:cached
      - /workspace/front/node_modules
    ports:
      - "4200:4200"
    command: sh -c "npm install --no-audit --no-fund && npm run start -- --host 0.0.0.0"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - back


volumes:
  mysql-data:
